# Generated by Django 4.2.16 on 2024-09-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('periodo', models.IntegerField()),
                ('concluida', models.BooleanField(default=False)),
                ('dependencias', models.ManyToManyField(blank=True, to='disciplinas.disciplina')),
            ],
        ),
    ]
